version: '3.8'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    image: appointment  # replace with the actual GraphQL image from Docker Hub
    ports:
      - "8000:8000"  # GraphQL server port
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}                         
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres 

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    # volumes:
    #   - graphql-volume:/var/lib/postgresql/data 
# volumes:
#     graphql-volume:
    
